apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-deployment
  labels:
    app: farm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
    spec:
      containers:
      - name: farm-api
        image: viniciusdelr/agrosolutions-farm:v1 # Certifique-se de usar a tag correta
        ports:
        - containerPort: 8080
        env:
        # Mesma conexão, pois o banco é unificado para o MVP [cite: 49]
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: agro-db-secret
              key: connection-string
        # Necessário para validar o token gerado pelo IdentityService [cite: 11]
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: agro-db-secret
              key: jwt-key
        - name: Jwt__Issuer
          value: "AgroSolutionsUsers"
        - name: Jwt__Audience
          value: "AgroSolutionsApps"