apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
    spec:
      containers:
      - name: farm-api
        image: viniciusdelr/agrosolutions-farm:v1 
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: agro-db-secret
              key: connection-string
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: agro-db-secret
              key: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: farm-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: farm